// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhiX5P5FbzAArLLq_sSLHs3nnl0MJ5Aiw',
    appId: '1:885991091403:web:936c1bc889630ae7c97f4e',
    messagingSenderId: '885991091403',
    projectId: 'onboard-ba2f2',
    authDomain: 'onboard-ba2f2.firebaseapp.com',
    storageBucket: 'onboard-ba2f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjiELMj4hqS7mI04EhdvdDD_BAmu4gFNg',
    appId: '1:885991091403:android:bea7185f1ceeacd0c97f4e',
    messagingSenderId: '885991091403',
    projectId: 'onboard-ba2f2',
    storageBucket: 'onboard-ba2f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSW3aHLMPlX6OcYyHEBmFajt4vBT-B1Yc',
    appId: '1:885991091403:ios:665229638c76a655c97f4e',
    messagingSenderId: '885991091403',
    projectId: 'onboard-ba2f2',
    storageBucket: 'onboard-ba2f2.appspot.com',
    iosBundleId: 'com.example.onboard',
  );
}
